services:
  web:
    container_name: codestra_container
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    networks:
      - odoo_proxy_network
    stdin_open: true
    tty: true