version: "3.8"

services:
  web:
    container_name: codestra_container
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always
    networks:
      - odoo_proxy_network

networks:
  odoo_proxy_network:
    external: true
