import { useState, type ReactNode } from "react";
import Footer from "../../Components/Layouts/Footer";
import Navbar from "../../Components/Layouts/Navbar";
import { businessProfile, formatMainOffice } from "../../config/businessProfile";
import { readCookieChoice, saveCookieChoice } from "../../Components/Consent/CookieConsent";

const Shell=({children}:{children:ReactNode})=><><Navbar/><main id="main-content" className="policy-page mx-auto min-h-[70vh] max-w-4xl px-5 pb-16 pt-32 leading-7 lg:pt-44">{children}</main><Footer/></>;
export function CookiePolicyPage(){return <Shell><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#FFD700]">Privacy controls</p><h1>Cookie Policy</h1><p>Effective {businessProfile.policy.effectiveDate} · Updated {businessProfile.policy.lastUpdated} · Version {businessProfile.policy.version}</p><div className="overflow-x-auto"><table><thead><tr><th>Name</th><th>Category</th><th>Purpose</th><th>Duration</th></tr></thead><tbody><tr><td>codestra_cookie_preferences_v1</td><td>Necessary</td><td>Stores the visitor's consent selection and source.</td><td>Until browser storage is cleared</td></tr><tr><td>codestra_analytics_consent</td><td>Necessary</td><td>Records whether optional analytics is allowed.</td><td>Until browser storage is cleared</td></tr><tr><td>codestra_locale</td><td>Functional</td><td>Remembers a language preference.</td><td>Until browser storage is cleared</td></tr><tr><td>codestra_attribution_v1</td><td>Analytics</td><td>Stores campaign attribution after analytics consent or during an initiated form workflow.</td><td>Until browser storage is cleared</td></tr><tr><td>codestra_anonymous_session_id</td><td>Analytics</td><td>Correlates consented analytics events without a customer account identifier.</td><td>Until browser storage is cleared</td></tr></tbody></table></div><p>Live advertising and AdSense storage are disabled. No Google-certified CMP is configured.</p></Shell>}
export function CookiePreferencesPage(){const [allowed,setAllowed]=useState(readCookieChoice()?.analytics??false);return <Shell><h1>Cookie Preferences</h1><p>Necessary storage cannot be disabled because it supports consent, language and requested site functions. Optional analytics can be changed or withdrawn below.</p><label className="my-6 flex min-h-11 items-center gap-3 rounded-xl border border-neutral-700 p-4"><input type="checkbox" checked={allowed} onChange={e=>setAllowed(e.target.checked)}/><span>Allow optional analytics</span></label><button className="rounded-full bg-[#FFD700] px-6 py-3 font-semibold text-black" onClick={()=>saveCookieChoice(allowed)}>Save selection</button></Shell>}
export function PrivacyChoicesPage(){return <Shell><h1>Privacy Choices</h1><p>To request access, correction or deletion of personal information, email <a href={`mailto:${businessProfile.privacyEmail}`}>{businessProfile.privacyEmail}</a> from an address Codestra can use to verify your request. Include the request type and the Codestra service involved; do not send identity documents until requested through a verified channel.</p><p>Codestra does not currently represent that it sells personal information. If practices change, this page and the Privacy Policy must be updated before the change takes effect.</p><p>{businessProfile.legalOperator.name}<br/>{formatMainOffice()}</p></Shell>}
export function CommunicationsPreferencesPage(){const withdraw=()=>{saveCookieChoice(false); localStorage.removeItem("codestra_attribution_v1"); localStorage.removeItem("codestra_anonymous_session_id");};return <Shell><h1>Communications Preferences</h1><p>Reply STOP to a Codestra text message to opt out of that text program. Reply HELP for help. Use the unsubscribe link in a marketing email to opt out of email marketing. Service and security notices may still be sent when necessary for an active account or requested service.</p><button className="my-5 rounded-full border border-neutral-600 px-6 py-3" onClick={withdraw}>Withdraw browser analytics consent</button><p>For a preference or suppression issue, contact <a href={`mailto:${businessProfile.supportEmail}`}>{businessProfile.supportEmail}</a>. Include the communication channel and destination you want suppressed.</p></Shell>}
